### Get all blogs
GET http://localhost:3003/api/blogs

### Add a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test Blog",
    "author": "John Doe",
    "url": "https://sigmablog.com",
    "likes": 7
}